on:
  issues:
    types:
      - reopened
      
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: https://github.com/users/thdtmdghks/projects/1/views/1
          column: In Progress
          repo-token: ${{ secrets.MY_TOKEN }}
