on:
  issues:
    types: [reopened, opened]
    
concurrency:
  group: update-projects-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  issues:
    runs-on: ubuntu-latest
    steps:
      # substitute RELEASE_VERSION for the latest version available in releases
      - uses: PaperMC/update-projects-action@v0.2.0
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          project-url: https://github.com/users/thdtmdghks/projects/1/views/1
          column-field: In Progress
