on:
  issues:
    types:
      - reopened
      
jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: test project
          column: Done
          repo-token: ${{ secrets.MY_TOKEN }}
